-- CreateTable
CREATE TABLE `Expences` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `Rent` INTEGER NOT NULL,
    `Salary` INTEGER NOT NULL,
    `tea` INTEGER NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
