-- AlterTable
ALTER TABLE "CustomerInvoice" ADD COLUMN     "totalCGST" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalGST" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalSGST" DOUBLE PRECISION NOT NULL DEFAULT 0;
