-- AlterTable
ALTER TABLE "User" ADD COLUMN     "createdBy" INTEGER,
ALTER COLUMN "role" SET DEFAULT 'MANAGER';

-- AddForeignKey
ALTER TABLE "User" ADD CONSTRAINT "User_createdBy_fkey" FOREIGN KEY ("createdBy") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
