-- CreateTable
CREATE TABLE `Product` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `code` INTEGER NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `frameType` ENUM('RIMLESS', 'METALLIC', 'SHEET') NOT NULL,
    `shapeType` ENUM('ROUND', 'SQUARE', 'HEXAGONE') NOT NULL,
    `visionType` ENUM('SINGLE_VISION', 'BI_FOCAL', 'PROGRESSIVE') NOT NULL,
    `coatingType` ENUM('WITHOUT_ANTI_GLARE', 'WITH_ANTI_GLARE', 'BLUE_BLOCK', 'PHOTOCHROMATIC', 'PHOTOCHROMATIC_WITH_ANTI_GLARE', 'PHOTOCHROMATIC_WITH_BLUE_BLOCK') NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `branchId` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Product` ADD CONSTRAINT `Product_branchId_fkey` FOREIGN KEY (`branchId`) REFERENCES `Branch`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
